### ISSUE TITLE
执行用例出错，

### ISSUE THREAD

**Issue by jooke** [radiateboy/automagic#11]
2018-04-13 16:33:15,015 [utils:execute] [DEBUG]- (0.002) SELECT `autoplat_case`.
`id`, `autoplat_case`.`projectid_id`, `autoplat_case`.`moduleid_id`, `autoplat_c
ase`.`testrailcaseid`, `autoplat_case`.`casedesc`, `autoplat_case`.`isenabled`,
`autoplat_case`.`issmoke`, `autoplat_case`.`dependent`, `autoplat_case`.`debugin
fo`, `autoplat_case`.`createtime`, `autoplat_case`.`createat`, `autoplat_case`.`
updatetime`, `autoplat_case`.`updateat` FROM `autoplat_case` WHERE `autoplat_cas
e`.`id` = 1; args=(1,)

DevTools listening on ws://127.0.0.1:12371/devtools/browser/4061aec4-c5eb-448c-8
e65-1d236b06ef45

Time Elapsed: 0:00:00
Traceback (most recent call last):
  File "seleniumkeyword/TestSuite.py", line 425, in <module>
    Controller.update_result()
  File "seleniumkeyword/TestSuite.py", line 240, in update_result
    Controller.my_execute(sql_str)
  File "seleniumkeyword/TestSuite.py", line 195, in my_execute
    cls.cur.execute(sql)
  File "C:\Python27\lib\site-packages\MySQLdb\cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defau
lterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax
; check the manual that corresponds to your MySQL server version for the right s
yntax to use near 'END WHERE id IN ()' at line 1")

**Comment by CL0406** [comment]
数据库版本问题吧。

**Comment by radiateboy** [comment]
更新到python3、django3.0.2版本，测试未发现类似问题，可以试试新版本。
