### ISSUE TITLE
使用远程数据库，用例执行失败

### ISSUE THREAD

**Issue by lihuacai168** [radiateboy/automagic#31]
- 随便输入一个用例，点击执行。数据库连接错误。数据库是远程连接的阿里云数据库
```
Traceback (most recent call last):
  File "seleniumkeyword/TestSuite.py", line 418, in <module>
    Controller.init()
  File "seleniumkeyword/TestSuite.py", line 174, in init
    cls.set_conn()
  File "seleniumkeyword/TestSuite.py", line 186, in set_conn
    charset='utf8')
  File "C:\my_data\python_virtual_envs\automagic\lib\site-packages\MySQLdb\__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "C:\my_data\python_virtual_envs\automagic\lib\site-packages\MySQLdb\connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (10061)")
[20/May/2020 14:29:29] "GET /func/case/run/?csrfmiddlewaretoken=6uSUvL7yv0bmlaJrIilRglT1eJHIuaPfj8KQHgesq7TfO4hSud3YYbH37PNGm4ZR&caseid=1&_=1589956162863 HTTP/1.1" 200 4
[20/May/2020 14:29:30] "GET /func/case/list/?check_productname=1&projectid=1&moduleid=&casestatus=&issmoke=&keyword= HTTP/1.1" 200 21776
```

**Comment by radiateboy** [comment]
@lihuacai168 执行脚本里面的数据库连接地址没改吧？ 看报错连接的还是 127.0.0.1
